version: '2'

services:
  base:
    image: newsfeed
    build:
      context: .
    volumes:
      - ./config.py:/app/config.py
    restart: always
    logging:
      options:
        max-size: '50M'
